{{- if .Values.oauth2Proxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-dashboard.fullname" . }}-oauth2
  labels:
    {{- include "k8s-dashboard.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-id: {{ .Values.oauth2Proxy.config.clientID | quote }}
  client-secret: {{ .Values.oauth2Proxy.config.clientSecret | quote }}
  cookie-secret: {{ .Values.oauth2Proxy.config.cookieSecret | quote }}
{{- end }}